name: Run Unit Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install
        run : npm install
        
      - name: lint
        run : npm run lint --fix
        
      - name: test
        run : npm run test:unit
        
      - run: npm install -g bundle-phobia-cli
      - run: npm install -g depcheck
      - name: Get Package Info
        uses: DesignrKnight/js-package-info@v2
        with:
          node_dir: './'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



              
