name: Run Unit Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install
        run : npm install
        
      - name: build
        run : npm run build:stage --fix
        
      - name: lint
        run : npm run lint
        
      - name: test
        run : npm run test:unit

              
